apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jeff-master-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jeff-master
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80