apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rps-sample
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: rps-sample
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Pods
    pods:
      metricName: requestspercount
      targetAverageValue: 100